import { Toaster } from 'react-hot-toast';

import './globals.css';

export const metadata = {
	title: 'Admin Dashboard',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
	return (
		<html lang='en'>
			<body suppressHydrationWarning={true} className='h-screen text-primary bg-primary'>
				<Toaster position='bottom-right' />
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
